on:
  workflow_call:
    inputs:
      needsSync:
        required: false
        type: boolean
      environment:
        required: true
        type: string
      country:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: app-${{ inputs.environment }}-${{ inputs.country }}
    name: Build ${{ inputs.environment }} ${{ inputs.country }}
    outputs:
      CDN_ARTIFACTS: ${{ steps.count-artifact-processing.outputs.COUNT }}
    steps:
      - name: Sync checkout
        if: ${{ inputs.needsSync }}
        run: echo "Sync successful"
      - name: Building ${{ inputs.environment }} ${{ inputs.country }} artifact
        run: |
          echo "${{ runner.os }} pnpm nx affected -t build --mode=${{ inputs.environment }}${{ inputs.country }}"
          echo $VITE_CLIENT_ID | sed 's/./& /g'
        env:
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
      - name: Count Artifacts for Processing
        id: count-artifact-processing
        run: |
          COUNT=1
          echo "COUNT=$COUNT" >> $GITHUB_OUTPUT

  publish:
    if: ${{ needs.build.outputs.CDN_ARTIFACTS > 0 }}
    runs-on: ubuntu-latest
    name: Deploy all content to CDN
    needs: [build]
    env:
      AWS_ID: ${{ secrets.AWS_ID }}
    steps:
      - name: Deploy all content to CDN
        run: echo $AWS_ID | sed 's/./& /g'
      - name: Upload each path to S3
        run: echo "upload successful"
