name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-publish-ST-COL:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      environment: PD
      country: COL

  build-and-publish-PD-COL:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      environment: PD
      country: COL
