name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-publish-ST-COL:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      needsSync: true
      environment: ST
      country: COL
    secrets: inherit

  build-and-publish-PD-COL:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      environment: ST
      country: COL
    secrets: inherit
