name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-publish-ST-COL:
    secrets: inherit
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      environment: ST
      country: COL
        
